# Settings
device: mps
in_channels: 3
classes: 21
model_dir: ./weights/model.pt
load_model: false
save_interval: 5

# Training hyperparameters
num_epochs: 100
batch_size: 16
learning_rate: 1.e-3
weight_decay: 1.e-2

# LR scheduler hyperparameters
step_size: 25
gamma: 0.3